services:

  banking-app:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile

    container_name: banking-app

    restart: unless-stopped

    ports:
      - "${APP_PORT}:8080"
      - "9404:9404"

    networks:
      - banking-network

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter

    restart: unless-stopped

    ports:
      - "9100:9100"

    command:
      - '--path.rootfs=/host'

    pid: host

    volumes:
      - '/:/host:ro,rslave'

    networks:
      - banking-network



  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor

    restart: unless-stopped

    ports:
      - "8088:8080"

    privileged: true

    devices:
      - /dev/kmsg

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

    networks:
      - banking-network

networks:

  banking-network:
    driver: bridge
