services:

  banking-blue:
    image: ${BANKING_IMAGE:-banking-app:latest}

    container_name: banking-blue

    restart: unless-stopped

    expose:
      - "8080"

    ports:
      - "9404:9404"
      - "9414:8080"

    volumes:
      - ./logs/blue:/usr/local/tomcat/logs

    networks:
      - banking-network


  banking-green:
    image: ${BANKING_IMAGE:-banking-app:latest}

    container_name: banking-green

    restart: unless-stopped

    expose:
      - "8080"

    ports:
      - "9405:9404"
      - "9415:8080"

    volumes:
      - ./logs/green:/usr/local/tomcat/logs

    networks:
      - banking-network

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter

    restart: unless-stopped

    ports:
      - "9100:9100"

    command:
      - '--path.rootfs=/host'
      - '--collector.textfile.directory=/host/var/lib/node_exporter/textfile_collector'

    pid: host

    volumes:
      - '/:/host:ro,rslave'

    networks:
      - banking-network



  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor

    restart: unless-stopped

    ports:
      - "8088:8080"

    privileged: true

    devices:
      - /dev/kmsg

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev/disk:/dev/disk:ro
 

    command:
      - --housekeeping_interval=10s

    networks:
      - banking-network


  nginx:
    image: nginx:alpine
    container_name: banking-nginx
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - banking-blue
      - banking-green

    networks:
      - banking-network

networks:

  banking-network:
    name: banking-app_banking-network
    driver: bridge
